name: Documentation

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - master
    paths:
      - "mkdocs.yml"
      - "Documentation/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Builds the documentation site according to the config in `mkdocs.yml` in the repo root.
      - name: Deploy MkDocs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.21
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
          REQUIREMENTS: Documentation/requirements.txt
